// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitoringProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MonitoringProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MonitoringProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MonitoringProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MonitoringProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MonitoringProtocol_2eproto;
namespace Protocol {
class M_REQ_SERVER_INFO;
struct M_REQ_SERVER_INFODefaultTypeInternal;
extern M_REQ_SERVER_INFODefaultTypeInternal _M_REQ_SERVER_INFO_default_instance_;
class S_RES_SERVER_INFO;
struct S_RES_SERVER_INFODefaultTypeInternal;
extern S_RES_SERVER_INFODefaultTypeInternal _S_RES_SERVER_INFO_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::M_REQ_SERVER_INFO* Arena::CreateMaybeMessage<::Protocol::M_REQ_SERVER_INFO>(Arena*);
template<> ::Protocol::S_RES_SERVER_INFO* Arena::CreateMaybeMessage<::Protocol::S_RES_SERVER_INFO>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class M_REQ_SERVER_INFO final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:Protocol.M_REQ_SERVER_INFO) */ {
 public:
  inline M_REQ_SERVER_INFO() : M_REQ_SERVER_INFO(nullptr) {}
  explicit PROTOBUF_CONSTEXPR M_REQ_SERVER_INFO(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  M_REQ_SERVER_INFO(const M_REQ_SERVER_INFO& from);
  M_REQ_SERVER_INFO(M_REQ_SERVER_INFO&& from) noexcept
    : M_REQ_SERVER_INFO() {
    *this = ::std::move(from);
  }

  inline M_REQ_SERVER_INFO& operator=(const M_REQ_SERVER_INFO& from) {
    CopyFrom(from);
    return *this;
  }
  inline M_REQ_SERVER_INFO& operator=(M_REQ_SERVER_INFO&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const M_REQ_SERVER_INFO& default_instance() {
    return *internal_default_instance();
  }
  static inline const M_REQ_SERVER_INFO* internal_default_instance() {
    return reinterpret_cast<const M_REQ_SERVER_INFO*>(
               &_M_REQ_SERVER_INFO_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(M_REQ_SERVER_INFO& a, M_REQ_SERVER_INFO& b) {
    a.Swap(&b);
  }
  inline void Swap(M_REQ_SERVER_INFO* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(M_REQ_SERVER_INFO* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  M_REQ_SERVER_INFO* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<M_REQ_SERVER_INFO>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const M_REQ_SERVER_INFO& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const M_REQ_SERVER_INFO& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.M_REQ_SERVER_INFO";
  }
  protected:
  explicit M_REQ_SERVER_INFO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.M_REQ_SERVER_INFO)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_MonitoringProtocol_2eproto;
};
// -------------------------------------------------------------------

class S_RES_SERVER_INFO final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_RES_SERVER_INFO) */ {
 public:
  inline S_RES_SERVER_INFO() : S_RES_SERVER_INFO(nullptr) {}
  ~S_RES_SERVER_INFO() override;
  explicit PROTOBUF_CONSTEXPR S_RES_SERVER_INFO(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_RES_SERVER_INFO(const S_RES_SERVER_INFO& from);
  S_RES_SERVER_INFO(S_RES_SERVER_INFO&& from) noexcept
    : S_RES_SERVER_INFO() {
    *this = ::std::move(from);
  }

  inline S_RES_SERVER_INFO& operator=(const S_RES_SERVER_INFO& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_RES_SERVER_INFO& operator=(S_RES_SERVER_INFO&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_RES_SERVER_INFO& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_RES_SERVER_INFO* internal_default_instance() {
    return reinterpret_cast<const S_RES_SERVER_INFO*>(
               &_S_RES_SERVER_INFO_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_RES_SERVER_INFO& a, S_RES_SERVER_INFO& b) {
    a.Swap(&b);
  }
  inline void Swap(S_RES_SERVER_INFO* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_RES_SERVER_INFO* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_RES_SERVER_INFO* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_RES_SERVER_INFO>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_RES_SERVER_INFO& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_RES_SERVER_INFO& from) {
    S_RES_SERVER_INFO::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_RES_SERVER_INFO* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_RES_SERVER_INFO";
  }
  protected:
  explicit S_RES_SERVER_INFO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGameSessionNumFieldNumber = 1,
  };
  // uint64 game_session_num = 1;
  void clear_game_session_num();
  uint64_t game_session_num() const;
  void set_game_session_num(uint64_t value);
  private:
  uint64_t _internal_game_session_num() const;
  void _internal_set_game_session_num(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_RES_SERVER_INFO)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t game_session_num_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MonitoringProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// M_REQ_SERVER_INFO

// -------------------------------------------------------------------

// S_RES_SERVER_INFO

// uint64 game_session_num = 1;
inline void S_RES_SERVER_INFO::clear_game_session_num() {
  _impl_.game_session_num_ = uint64_t{0u};
}
inline uint64_t S_RES_SERVER_INFO::_internal_game_session_num() const {
  return _impl_.game_session_num_;
}
inline uint64_t S_RES_SERVER_INFO::game_session_num() const {
  // @@protoc_insertion_point(field_get:Protocol.S_RES_SERVER_INFO.game_session_num)
  return _internal_game_session_num();
}
inline void S_RES_SERVER_INFO::_internal_set_game_session_num(uint64_t value) {
  
  _impl_.game_session_num_ = value;
}
inline void S_RES_SERVER_INFO::set_game_session_num(uint64_t value) {
  _internal_set_game_session_num(value);
  // @@protoc_insertion_point(field_set:Protocol.S_RES_SERVER_INFO.game_session_num)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MonitoringProtocol_2eproto
